version: '3'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.16
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=myMasterKey123 # CHANGE THIS for production!
    volumes:
      - ./meili_data:/meili_data
